### ISSUE TITLE
Problemas con el deploy

### ISSUE THREAD

**Issue by d0dzv** [IIC3103-2024-02/help#76]
Hola!
Estoy deployeando el back mediante render, pero estoy teniendo problemas con los requirements, al principio me salía que requirements.txt tenía líneas de texto exclusivas de ubuntu que provocaban error, luego de borrarlas todas me aparece el siguiente error:
```
==> Cloning from https://github.com/...
==> Checking out commit fc36dd7e292e399341ffb6b935b9b1bd09d5c717 in branch main
==> Using Python version 3.11.10 (default)
==> Docs on specifying a Python version: https://render.com/docs/python-version
==> Using Poetry version 1.7.1 (default)
==> Docs on specifying a Poetry version: https://render.com/docs/poetry-version
==> Running build command 'pip install -r requirements.txt'...
Collecting annotated-types==0.7.0 (from -r requirements.txt (line 1))
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting anyio==4.4.0 (from -r requirements.txt (line 2))
  Downloading anyio-4.4.0-py3-none-any.whl.metadata (4.6 kB)
Collecting APScheduler==3.10.4 (from -r requirements.txt (line 3))
  Downloading APScheduler-3.10.4-py3-none-any.whl.metadata (5.7 kB)
Collecting asgiref==3.5.0 (from -r requirements.txt (line 4))
  Downloading asgiref-3.5.0-py3-none-any.whl.metadata (9.2 kB)
Collecting bcrypt==4.2.0 (from -r requirements.txt (line 5))
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting blinker==1.8.2 (from -r requirements.txt (line 6))
  Downloading blinker-1.8.2-py3-none-any.whl.metadata (1.6 kB)
Collecting certifi==2024.8.30 (from -r requirements.txt (line 7))
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting cffi==1.17.1 (from -r requirements.txt (line 8))
  Downloading cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting charset-normalizer==3.4.0 (from -r requirements.txt (line 9))
  Downloading charset_normalizer-3.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (34 kB)
Collecting click==8.1.7 (from -r requirements.txt (line 10))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama==0.4.4 (from -r requirements.txt (line 11))
  Downloading colorama-0.4.4-py2.py3-none-any.whl.metadata (14 kB)
Collecting cryptography==3.4.8 (from -r requirements.txt (line 12))
  Downloading cryptography-3.4.8-cp36-abi3-manylinux_2_24_x86_64.whl.metadata (5.2 kB)
Collecting exceptiongroup==1.2.2 (from -r requirements.txt (line 13))
  Downloading exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting fastapi==0.112.2 (from -r requirements.txt (line 14))
  Downloading fastapi-0.112.2-py3-none-any.whl.metadata (27 kB)
Collecting Flask==3.0.3 (from -r requirements.txt (line 15))
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting h11==0.14.0 (from -r requirements.txt (line 16))
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting httplib2==0.20.2 (from -r requirements.txt (line 17))
  Downloading httplib2-0.20.2-py3-none-any.whl.metadata (2.5 kB)
Collecting idna==3.8 (from -r requirements.txt (line 18))
  Downloading idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting importlib-metadata==4.6.4 (from -r requirements.txt (line 19))
  Downloading importlib_metadata-4.6.4-py3-none-any.whl.metadata (4.0 kB)
Collecting itsdangerous==2.2.0 (from -r requirements.txt (line 20))
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting Jinja2==3.1.4 (from -r requirements.txt (line 21))
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting MarkupSafe==3.0.2 (from -r requirements.txt (line 22))
  Downloading MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Collecting more-itertools==8.10.0 (from -r requirements.txt (line 23))
  Downloading more_itertools-8.10.0-py3-none-any.whl.metadata (36 kB)
Collecting numpy==2.1.2 (from -r requirements.txt (line 24))
  Downloading numpy-2.1.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 353.0 kB/s eta 0:00:00
Collecting oauthlib==3.2.0 (from -r requirements.txt (line 25))
  Downloading oauthlib-3.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting paramiko==3.5.0 (from -r requirements.txt (line 26))
  Downloading paramiko-3.5.0-py3-none-any.whl.metadata (4.4 kB)
Collecting pinecone-client==5.0.1 (from -r requirements.txt (line 27))
  Downloading pinecone_client-5.0.1-py3-none-any.whl.metadata (19 kB)
Collecting pinecone-plugin-inference==1.1.0 (from -r requirements.txt (line 28))
  Downloading pinecone_plugin_inference-1.1.0-py3-none-any.whl.metadata (2.2 kB)
Collecting pinecone-plugin-interface==0.0.7 (from -r requirements.txt (line 29))
  Downloading pinecone_plugin_interface-0.0.7-py3-none-any.whl.metadata (1.2 kB)
Collecting psycopg2==2.9.10 (from -r requirements.txt (line 30))
  Downloading psycopg2-2.9.10.tar.gz (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.7/385.7 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pycparser==2.22 (from -r requirements.txt (line 31))
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting pydantic==2.8.2 (from -r requirements.txt (line 32))
  Downloading pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.2/125.2 kB 11.5 MB/s eta 0:00:00
Collecting pydantic_core==2.20.1 (from -r requirements.txt (line 33))
  Downloading pydantic_core-2.20.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting PyJWT==2.3.0 (from -r requirements.txt (line 34))
  Downloading PyJWT-2.3.0-py3-none-any.whl.metadata (4.0 kB)
Collecting PyNaCl==1.5.0 (from -r requirements.txt (line 35))
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (8.6 kB)
Collecting pyparsing==2.4.7 (from -r requirements.txt (line 36))
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting python-dotenv==1.0.1 (from -r requirements.txt (line 37))
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting pytz==2024.2 (from -r requirements.txt (line 38))
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting PyYAML==5.4.1 (from -r requirements.txt (line 39))
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 18.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/render/project/src/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 312, in run
          self.find_sources()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 320, in find_sources
          mm.run()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 579, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-akteqdek/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
==> Build failed 😞
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys
```
Llevo toda la tarde intentando solucionarlo y ya se me acabaron las ideas, agradecería cualquier orientación.
De antemano, muchas gracias.

**Comment by terelopezc** [comment]
Hola @d0dzv 
Te recomiendo probar con vercel o Netlify. Puedes estar teniendo problemas con la capa gratuita de render (otros alumnos han tenido ese problema).
